# Run modes
GENERATE_OPTIMAL = 0
BRANCHING = 1
MODE = [
    'GENERATE OPTIMAL',
    'BRANCHING'
]

# CPLEX sense constant
MINIMIZE = 1

# CPLEX status constant
LP_OPTIMAL = 1
LP_INFEASIBLE = 3
LP_ABORT_IT_LIM = 10
INFEASIBILITY = 1e-6

# CPLEX branch creation constants
UPPER_BOUND = 'U'
LOWER_BOUND = 'L'

# Branch strategy constants
BS_DEFAULT = 0
BS_SB = 1
BS_PC = 2
BS_SB_PC = 3
BS_SB_ML_SVMRank = 4
BS_SB_ML_LR = 5
BS_SB_ML_NN = 6
BS_SB_ML_GNN = 7
STRATEGY = [
    'DEFAULT',
    'STRONG BRANCHING',
    'PSEUDOCOST BRANCHING',
    'STRONG+PSEUDOCOST BRANCHING',
    'SVM RANK',
    'LINEAR REGRESSION',
    'FEEDFORWARD NEURAL NETWORK',
    'GRAPH NEURAL NETWORK'
]
